version: '3.7'

services:
  node:
    image: cenk1cenk2/node-fnm:latest
    environment:
      SERVICE_0_CWD: .
      SERVICE_0_COMMAND: pnpm run dev:start
    ports:
      - 5173:5173
      - 9229:9229
    volumes:
      - .:/data
