packages:
  - docs
  - examples
  - packages/*

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@cenk1cenk2/*'

allowBuilds:
  '@swc/core': true
  esbuild: false
  simple-git-hooks: true
  unrs-resolver: true
