export enum ListrDefaultRendererLogLevels {
  SKIPPED_WITH_COLLAPSE = 'SKIPPED_WITH_COLLAPSE',
  SKIPPED_WITHOUT_COLLAPSE = 'SKIPPED_WITHOUT_COLLAPSE',
  OUTPUT = 'OUTPUT',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  COMPLETED_WITH_FAILED_SUBTASKS = 'COMPLETED_WITH_FAILED_SUBTASKS',
  COMPLETED_WITH_SISTER_TASKS_FAILED = 'COMPLETED_WITH_SISTER_TASKS_FAILED',
  RETRY = 'RETRY',
  ROLLING_BACK = 'ROLLING_BACK',
  ROLLED_BACK = 'ROLLED_BACK',
  FAILED = 'FAILED',
  FAILED_WITH_FAILED_SUBTASKS = 'FAILED_WITH_SUBTASKS',
  WAITING = 'WAITING'
}
